---
title: "model_binary"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(scales)

tidy_data <- read_csv("data/tidy_data/tidy_data_verifiable.csv")

tidy_data <- tidy_data %>%
        mutate(presence_projects = as.factor(ifelse(n_projects == 0, "no", "yes")),
               presence_obs_fields = as.factor(ifelse(n_obs_fields == 0, "no", "yes")),
               presence_tags = as.factor(ifelse(n_tags == 0, "no", "yes")),
               presence_notes = as.factor(presence_notes),
               microscopy_project = as.factor(microscopy_project),
               created_at_month = factor(
                       created_at_month, levels = month.abb, ordered = TRUE),
               genus = as.factor(genus)) %>% 
        
        select("id", "uri", "quality_grade", "created_at", "taxon_id", "n_photos",
               "microscopy_project","days_since_upload", "created_at_year", 
               "observed_on_year", "created_at_month","observed_on_month", "country",
               "kingdom", "phylum", "class", "order", "family","genus", "specificEpithet", "taxon_rank",
               "sum_pixels", "n_obs_fields", "n_tags", "n_projects", "length_notes",
               "presence_projects", "presence_obs_fields", "presence_tags", 
               "presence_notes") %>% 
        
        filter(!is.na(sum_pixels) & n_photos != 0) %>% #filter out 0 photos obs (likely a bug)
        mutate(quality_sp_level = ifelse(quality_grade == "research" & specificEpithet == "Not identified", "needs_id", quality_grade), 
               rg = as.numeric(quality_sp_level == "research"),
               mean_pixels = sum_pixels/n_photos,
               log_mp = log10(mean_pixels),
               log_photos = log10(n_photos),
               yeas_since_upload = ceiling((days_since_upload + 1)/365), # day of upload = 1 
               log_ysu = log10(yeas_since_upload)) %>% 
        rescale(log_mp, to = c(0, 1))
        

data <- tidy_data %>%
        filter(genus != "Not identified") %>% 
        group_by(genus) %>% 
        filter(n() >= 10) %>% 
        ungroup 

data_rescale <- data %>% 
        mutate(log_mp_rescaled = rescale(log_mp, to = c(0, 1)))
```

Full model, including interaction. Log of mean of pixels was not rescaled.

```{r}
fit_all <- lme4::glmer(rg ~ log_ysu + log_photos + presence_notes + presence_tags + presence_obs_fields+ presence_projects + log_mp + microscopy_project + log_photos:microscopy_project + (1 | created_at_month) + (1 | genus), data= data, family = binomial,  na.action = na.fail)
                               
summary(fit_all)
```

```{r}
drop1(fit_all)
```

```         
Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00556903 (tol = 0.002, component 1)
Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0063805 (tol = 0.002, component 1)
Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0037219 (tol = 0.002, component 1)
Single term deletions

Model:
rg ~ log_ysu + log_photos + presence_notes + presence_tags + 
    presence_obs_fields + presence_projects + log_mp + microscopy_project + 
    log_photos:microscopy_project + (1 | created_at_month) + 
    (1 | genus)
                              npar     AIC
<none>                             2361383  # best model (lowest AIC)
log_ysu                          1 2379578  # 18 195 
presence_notes                   1 2363264  # 1 881 
presence_tags                    1 2361420  # 37 
presence_obs_fields              1 2363747  # 2 364 
presence_projects                1 2362032  # 649 
log_mp                           1 2361392  # 9 
log_photos:microscopy_project    1 2361386  # 3 - higher but within 6 - keep model w/o int.
```

Model without interaction:

```{r}
fit_no_interaction <- lme4::glmer(rg ~ log_ysu + log_photos + presence_notes + presence_tags + presence_obs_fields + log_mp + presence_projects + microscopy_project + (1|created_at_month) + (1 | genus), data= data, family = binomial,  na.action = na.fail)

summary(fit_no_interaction)
```

```         
Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
 Family: binomial  ( logit )
Formula: rg ~ log_ysu + log_photos + presence_notes + presence_tags +      presence_obs_fields + log_mp + presence_projects + microscopy_project +      (1 | created_at_month) + (1 | genus)
   Data: data

     AIC      BIC   logLik deviance df.resid 
 2361386  2361525 -1180682  2361364  2148071 

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-12.1477  -0.6769  -0.3556   0.7071  11.7663 

Random effects:
 Groups           Name        Variance Std.Dev.
 genus            (Intercept) 1.82304  1.3502  
 created_at_month (Intercept) 0.02764  0.1662  
Number of obs: 2148082, groups:  genus, 1277; created_at_month, 12

Fixed effects:
                        Estimate Std. Error z value Pr(>|z|)    
(Intercept)            -0.568512   0.062726  -9.063  < 2e-16 ***
log_ysu                 0.834844   0.006193 134.798  < 2e-16 ***
log_photos              0.180024   0.006662  27.023  < 2e-16 ***
presence_notesyes       0.226176   0.005188  43.599  < 2e-16 ***
presence_tagsyes        0.073290   0.011548   6.346  2.2e-10 ***
presence_obs_fieldsyes  0.534647   0.010966  48.756  < 2e-16 ***
log_mp                 -0.034778   0.008985  -3.871 0.000109 ***
presence_projectsyes    0.196244   0.007603  25.813  < 2e-16 ***
microscopy_projectyes   0.520141   0.026204  19.850  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) log_ys lg_pht prsnc_n prsnc_t prsn__ log_mp prsnc_p
log_ysu     -0.035                                                    
log_photos   0.022  0.065                                             
prsnc_ntsys -0.028 -0.021 -0.099                                      
prsnc_tgsys -0.021 -0.023 -0.018 -0.082                               
prsnc_bs_fl -0.015  0.012 -0.021 -0.047  -0.021                       
log_mp      -0.601  0.023 -0.050  0.022   0.040   0.028               
prsnc_prjct -0.011 -0.076  0.009 -0.012  -0.042  -0.195  0.011        
mcrscpy_prj -0.024  0.031 -0.115 -0.077   0.006  -0.015  0.023 -0.231 
```

```{r}
fit_all <- lme4::glmer(rg ~ log_ysu + log_photos + presence_notes + presence_tags + presence_obs_fields+ presence_projects + log_mp + microscopy_project + log_photos:microscopy_project + (1 | created_at_month) + (1 | genus), data= data, family = binomial,  na.action = na.fail)
```

Rescaling logmp

Full model runs with warning

```         
Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00222048 (tol = 0.002, component 1)
```

```{r}
fit_all_rescale <- lme4::glmer(rg ~ log_ysu + log_photos + presence_notes + presence_tags + presence_obs_fields+ presence_projects + log_mp_rescaled + microscopy_project + log_photos:microscopy_project + (1 | created_at_month) + (1 | genus), data= data_rescale, family = binomial,  na.action = na.fail)

summary(fit_all_rescale)
```

```{r}
drop1(fit_all_rescale)
```

```         
Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00212028 (tol = 0.002, component 1)
Single term deletions

Model:
rg ~ log_ysu + log_photos + presence_notes + presence_tags + 
    presence_obs_fields + presence_projects + log_mp_rescaled + 
    microscopy_project + log_photos:microscopy_project + (1 | 
    created_at_month) + (1 | genus)
                              npar     AIC
<none>                             2361383
log_ysu                          1 2379578
presence_notes                   1 2363264
presence_tags                    1 2361420
presence_obs_fields              1 2363747
presence_projects                1 2362032
log_mp_rescaled                  1 2361392
log_photos:microscopy_project    1 2361386
```

```{r}
fit_all_rescale_no_interaction <- lme4::glmer(rg ~ log_ysu + log_photos + presence_notes + presence_tags + presence_obs_fields+ presence_projects + log_mp_rescaled + microscopy_project + (1 | created_at_month) + (1 | genus), data= data_rescale, family = binomial,  na.action = na.fail)
```

```{r}
summary(fit_all_rescale_no_interaction)
```

```         
Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
 Family: binomial  ( logit )
Formula: rg ~ log_ysu + log_photos + presence_notes + presence_tags +  
    presence_obs_fields + presence_projects + log_mp_rescaled +  
    microscopy_project + (1 | created_at_month) + (1 | genus)
   Data: data_rescale

     AIC      BIC   logLik deviance df.resid 
 2361386  2361525 -1180682  2361364  2148071 

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-12.1477  -0.6769  -0.3556   0.7071  11.7663 

Random effects:
 Groups           Name        Variance Std.Dev.
 genus            (Intercept) 1.82304  1.3502  
 created_at_month (Intercept) 0.02763  0.1662  
Number of obs: 2148082, groups:  genus, 1277; created_at_month, 12

Fixed effects:
                        Estimate Std. Error z value Pr(>|z|)    
(Intercept)            -0.691186   0.048976 -14.113  < 2e-16 ***
log_ysu                 0.834840   0.006195 134.770  < 2e-16 ***
log_photos              0.180024   0.006659  27.035  < 2e-16 ***
presence_notesyes       0.226175   0.005188  43.600  < 2e-16 ***
presence_tagsyes        0.073293   0.011636   6.299    3e-10 ***
presence_obs_fieldsyes  0.534651   0.010991  48.643  < 2e-16 ***
presence_projectsyes    0.196244   0.007619  25.757  < 2e-16 ***
log_mp_rescaled        -0.107613   0.029604  -3.635 0.000278 ***
microscopy_projectyes   0.520160   0.025980  20.022  < 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
            (Intr) log_ys lg_pht prsnc_n prsnc_t prsn__ prsnc_p lg_mp_
log_ysu     -0.033                                                    
log_photos  -0.008  0.064                                             
prsnc_ntsys -0.028 -0.020 -0.099                                      
prsnc_tgsys -0.008 -0.022 -0.019 -0.082                               
prsnc_bs_fl -0.011  0.011 -0.019 -0.047  -0.014                       
prsnc_prjct -0.014 -0.074  0.010 -0.012  -0.044  -0.197               
lg_mp_rscld -0.307  0.029 -0.035  0.030   0.037   0.024  0.017        
mcrscpy_prj  0.001  0.028 -0.116 -0.072   0.009  -0.016 -0.234   0.006
```

```{r}
drop1(fit_all_rescale_no_interaction)
```

```         
Single term deletions

Model:
rg ~ log_ysu + log_photos + presence_notes + presence_tags + 
    presence_obs_fields + presence_projects + log_mp_rescaled + 
    microscopy_project + (1 | created_at_month) + (1 | genus)
                    npar     AIC
<none>                   2361386
log_ysu                1 2379579
log_photos             1 2362107
presence_notes         1 2363267
presence_tags          1 2361424
presence_obs_fields    1 2363747
presence_projects      1 2362036
log_mp_rescaled        1 2361395
microscopy_project     1 2361735
```
