---
title: "EDA_iNat_prop"
format: html
editor: visual
---

```{r}
#| code-fold: true
#| output: false
library(tidyverse)

iNat_counts<- read_csv("../data/iNat_country_prop.csv")

iNat_global_eu <-  read_csv("../data/iNat_prop_global_europe.csv")

```

```{r}

iNat_global_eu$prop_fungi_all = iNat_global_eu$n_fungi_all / (iNat_global_eu$n_fungi_all + iNat_global_eu$n_plants_all + iNat_global_eu$n_animals_all)

ggplot(iNat_global_eu, aes(x = fct_reorder(region, desc(prop_fungi_all)), y = prop_fungi_all)) +
        geom_bar(stat = "identity") + 
        theme_minimal()+
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(iNat_counts, aes(x = fct_reorder(country, desc(prop_fungi_all)), y = prop_fungi_all)) +
        geom_bar(stat = "identity") +
        theme_minimal()+
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
ggplot(iNat_counts, aes(x = fct_reorder(country, desc(prop_fungi_verifiable)), y = prop_fungi_verifiable)) +
        geom_bar(stat = "identity") +
        theme_minimal()+
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#| code-fold: true
#| output: false
library(tidyverse)

gbif_counts <- read_csv("../data/gbif_country_prop.csv")

gbif_counts <- rename(gbif_counts, country = name)
```

```{r}
ggplot(gbif_counts, aes(x = fct_reorder(country, desc(prop_fungi)), y = prop_fungi)) +
        geom_bar(stat = "identity") +
        theme_minimal()+
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
#| code-fold: true
#| output: false
library(tidyverse)

gbif_counts_filtered <- read_csv("../data/gbif_country_prop_filtered.csv")

gbif_counts_filtered <- rename(gbif_counts_filtered, country = name)


```

```{r}
ggplot(gbif_counts_filtered, aes(x = fct_reorder(country, desc(prop_fungi)), y = prop_fungi)) +
        geom_bar(stat = "identity") +
        theme_minimal()+
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
