---
title: "EDA - all data"
format: html
editor: visual
---

```{r}
#| code-fold: true 
#| output: false

library(tidyverse)
tidy_data_all <- read_csv("../data/tidy_data/new_combined_data.csv")
```

```{r}
#| label: fig quality grade
#| code-fold: true 

p <- ggplot(tidy_data_all,aes(x = fct_infreq(quality_grade), fill= quality_grade)) +
        geom_bar() +
        scale_fill_manual(values = c(research= "#a8cc08", needs_id= "#ffee91",casual= "#aaaaaa"))+
        labs(x = "Quality Grade", 
             y = "Number of observations") +
        #geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.6)+
        theme_classic(base_size = 14) +
        theme(axis.title.x = element_text(margin = margin(t = 10)),
              axis.title.y = element_text(margin = margin(r = 10)),
              legend.position = "none") 

p
```

**Note:** only verifiable observations are included in the rest of the analysis (i.e. Needs ID and RG). **Casual observations were excluded** since they can't be upgraded to RG.

```{r}
#| code-fold: true
#ggsave("../figs/quality_grade_observations.pdf", plot = p, width = 8, height = 6)
```

Number of observations:

```{r}
#| code-fold: true

n_RG <- tidy_data_all %>% 
        filter(quality_grade == "research") %>% 
        nrow()

n_needs_id <- tidy_data_all %>% 
        filter(quality_grade == "needs_id") %>% 
        nrow()

n_casual <- tidy_data_all %>% 
        filter(quality_grade == "casual") %>% 
        nrow()

print(paste("Total number of observations:", nrow(tidy_data_all)))
print(paste("Number of verifiable observations:", (n_RG + n_needs_id)))
print(paste("Number of RG observations", n_RG))
print(paste("Number of Needs ID observations:", n_needs_id))
print(paste("Number of Casual observations:", n_casual))

```
